FROM python:3.6-slim-stretch

RUN apt update
RUN apt install -y python3-dev gcc

# Install pytorch and fastai
RUN pip install torch_nightly -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
RUN pip install fastai

# Install starlette and uvicorn
RUN pip install flask
# TODO: Fix flask version

ADD model-weights.pth model-weights.pth

ADD server.py server.py


EXPOSE $PORT

# Start the server
CMD ["python", "server.py"]
